### PR TITLE
Setup quarto

### PR DESCRIPTION
**Pull request by NeuroShepherd**

### CODE REVIEW

**Comment by NeuroShepherd** [comment]
@MalikaIhle here's a rough draft of the site using Quarto

```
git checkout setup_quarto
quarto preview
```

^Should be sufficient to preview the project locally

**Comment by MalikaIhle** [comment]
Hi cool !
but how to I pull your branch locally? Should I merge and see what happens?

**Comment by MalikaIhle** [comment]
error: The following untracked working tree files would be overwritten by checkout:
        Introduction-RStudio-Git-GitHub.Rproj
Please move or remove them before you switch branches.
Aborting

**Comment by NeuroShepherd** [comment]
Do you have an uncommitted file `Introduction-RStudio-Git-GitHub.Rproj` in use? You can run `git stash` to hide it away for now.

**Comment by MalikaIhle** [comment]
yes the .Rproj to open this project. git stash says: no local changes to save. I dont usually commit the .Rproj file because people create new project and give it the name they want - or do you think it's better to commit RProj files ? what happens when people clone?

**Comment by NeuroShepherd** [comment]
I always commit the .Rproj file, and people cloning the repo can either use it or not

**Comment by MalikaIhle** [comment]
ok I moved my Rproj file elshwere and will move it back in when cheked out to main? 

I've rendered the qurot website: the link in the readme don't work: they link to .md files that don't exist. if I replcae by .qmd, it opens a text file non rendered. would that then be deployed through your github action? so I can't see it working in my local envt?

**Comment by NeuroShepherd** [comment]
@MalikaIhle fixed the links. You can pull down the updates and preview again.

**Comment by MalikaIhle** [comment]
Thanks that looks like all is working - we can put branding later on. I'll merge now.

**Pull request merged**
